trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: devops-ai-agent-group  # Variable group containing openai_api_key
- name: azureSubscription
  value: 'my-app-ado-con'
- name: azureResourceGroup
  value: 'opscart-hub_group'
- name: azureAppName
  value: 'hello-ai-java'
- name: javaVersion
  value: '17'
- name: SPRING_AI_OPENAI_API_KEY
  value: $(openai_api_key)  # from variable group
- name: SPRING_AI_OPENAI_BASE_URL
  value: https://api.openai.com

steps:
# 1. Install Java
- script: |
    sudo apt-get update
    sudo apt-get install -y openjdk-17-jdk
    java -version
  displayName: 'Install Java 17'

# 2. Debug - verify env vars in pipeline
- script: |
    echo "API KEY: $SPRING_AI_OPENAI_API_KEY"
    echo "BASE URL: $SPRING_AI_OPENAI_BASE_URL"
  displayName: 'Debug Spring Vars'

- script: |
    printenv | grep SPRING
  displayName: 'Debug - Print SPRING_* env vars'

# 3. Build with Maven
- script: |
    cd ai-chat-demo
    mvn clean package \
      -Dspring.ai.openai.api-key=$(SPRING_AI_OPENAI_API_KEY) \
      -Dspring.ai.openai.base-url=$(SPRING_AI_OPENAI_BASE_URL)
  displayName: 'Build with Maven'

# 4. Set App Service environment variables at runtime
- task: AzureCLI@2
  inputs:
    azureSubscription: $(azureSubscription)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      echo "Updating App Service environment variables..."
      az webapp config appsettings set \
        --name $(azureAppName) \
        --resource-group $(azureResourceGroup) \
        --settings \
          SPRING_AI_OPENAI_API_KEY=$(SPRING_AI_OPENAI_API_KEY) \
          SPRING_AI_OPENAI_BASE_URL=$(SPRING_AI_OPENAI_BASE_URL)

# 5. Deploy to Azure App Service
- task: AzureWebApp@1
  inputs:
    azureSubscription: '$(azureSubscription)'
    appType: 'webAppLinux'
    appName: '$(azureAppName)'
    resourceGroupName: '$(azureResourceGroup)'
    package: 'ai-chat-demo/target/*.jar'