trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: devops-ai-agent-group  # 👈 Link the variable group here
- name: azureSubscription
  value: 'my-app-ado-con'
- name: azureResourceGroup
  value: 'java-ai-rg'
- name: azureAppName
  value: 'hello-ai-java'
- name: javaVersion
  value: '17'
- name: SPRING_AI_AZURE_OPENAI_ENDPOINT
  value: $(azure_openai_endpoint
- name: SPRING_AI_OPENAI_API_KEY
  value: $(openai_api_key)  # 👈 This will now resolve correctly from the group

steps:
- script: |
    sudo apt-get update
    sudo apt-get install -y openjdk-17-jdk
    java -version
  displayName: 'Install Java 17'

- script: |
    echo "Key is: $(SPRING_AI_OPENAI_API_KEY)"
  displayName: 'Debug - Print API Key (for troubleshooting only)'

- script: |
    cd ai-chat-demo
    mvn clean package -Dspring.ai.azure.openai.api-key=$(SPRING_AI_OPENAI_API_KEY) -Dspring.ai.azure.openai.endpoint=$(SPRING_AI_AZURE_OPENAI_ENDPOINT)
  displayName: 'Build with Maven'

- task: AzureWebApp@1
  inputs:
    azureSubscription: '$(azureSubscription)'
    appType: 'webAppLinux'
    appName: '$(azureAppName)'
    resourceGroupName: '$(azureResourceGroup)'
    package: 'target/*.jar'
