trigger:
- main   # or your default branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'my-app-ado-con'
  azureResourceGroup: 'java-ai-rg'           # Use your resource group name
  azureAppName: 'hello-ai-java'            # Use the app name from previous step
  javaVersion: '17'
  SPRING_AI_OPENAI_API_KEY: $(openai_api_key)


steps:
- script: |
    sudo apt-get update
    sudo apt-get install -y openjdk-17-jdk
    java -version
  displayName: 'Install Java 17'

- script: |
    cd ai-chat-demo
    mvn clean package -Dspring.ai.openai.api-key=$(SPRING_AI_OPENAI_API_KEY)
  displayName: 'Build with Maven'

- task: AzureWebApp@1
  inputs:
    azureSubscription: '$(azureSubscription)'
    appType: 'webAppLinux'
    appName: '$(azureAppName)'
    resourceGroupName: '$(azureResourceGroup)'
    package: 'target/*.jar'
