trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: devops-ai-agent-group  # 👈 Link the variable group here
- name: azureSubscription
  value: 'my-app-ado-con'
- name: azureResourceGroup
  value: 'java-ai-rg'
- name: azureAppName
  value: 'hello-ai-java'
- name: javaVersion
  value: '17'
- name: SPRING_AI_OPENAI_API_KEY
  value: $(openai_api_key)  # 👈 This will now resolve correctly from the group
- name: SPRING_AI_OPENAI_BASE_URL
  value: https://api.openai.com
steps:
- script: |
    sudo apt-get update
    sudo apt-get install -y openjdk-17-jdk
    java -version
  displayName: 'Install Java 17'

- script: |
    echo "API KEY: $SPRING_AI_OPENAI_API_KEY"
    echo "BASE URL: $SPRING_AI_OPENAI_BASE_URL"
  displayName: 'Debug Spring Vars'

- script: |
    printenv | grep SPRING
  displayName: 'Debug - Print SPRING_* env vars'

- script: |
    cd ai-chat-demo
    mvn clean package \
      -Dspring.ai.openai.api-key=$(SPRING_AI_OPENAI_API_KEY) \
      -Dspring.ai.openai.base-url=$(SPRING_AI_OPENAI_BASE_URL)
  displayName: 'Build with Maven'

- task: AzureWebApp@1
  inputs:
    azureSubscription: '$(azureSubscription)'
    appType: 'webAppLinux'
    appName: '$(azureAppName)'
    resourceGroupName: '$(azureResourceGroup)'
    package: 'target/*.jar'
